### ISSUE TITLE
Module translation: Variable declaration: var, const, let

### ISSUE THREAD

**Issue by giocodes** [giocodes/modern-js-cheatsheet#2]
I've completed the translation for:
* Variable declaration: var, const, let

Please provide some feedback to confirm that everything looks good.

**Comment by jen-v** [comment]
hey @giocodes would you open a PR to leave some comments? :)

**Comment by giocodes** [comment]
Hi @jen-v, I've created #5 PR 
Since the text was already merged into master I just made a simple change to create a branch for this. Let me know if that works. 😊
